apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  chart:
    spec:
      chart: gateway-helm
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: flux-system
      version: v0.6.0
  interval: 15m
  releaseName: envoy-gateway
  timeout: 5m
  values:
