apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  chart:
    spec:
      chart: descheduler
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: descheduler
  values:
