apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
    recurring-job.longhorn.io/hourly-snap: enabled
    recurring-job.longhorn.io/source: enabled
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-ssd
